name: ðŸ“¦ Prepare Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
      - CHANGELOG.md

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: ðŸ“¦ Prepare Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: ðŸ‘¤ Setup git user
        run: |
          git config --global user.name "maciek-bot"
          git config --global user.email "maciek.gh.bot@gmail.com"

      - name: ðŸ†™ Set new version
        id: set_version
        # Currently, there is no way to customize PR title and commit message in the action. As a workaround,
        # we can use `changeset status` command to get the new version and then use it in the next steps.
        # ðŸ”— See: https://github.com/changesets/action/issues/303#issuecomment-1888167265
        run: |
          npm run changeset status -- --output=release.json
          NEW_VERSION=$(jq -r '.releases[0].newVersion' release.json)
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT
          rm release.json

      - name: ðŸ”€ Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: 'release v${{ steps.set_version.outputs.NEW_VERSION }}'
          commit: 'release v${{ steps.set_version.outputs.NEW_VERSION }}'
          setupGitUser: false
          version: bun run changeset:version
          publish: bun run changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
